/*
 * WARNING: this is an autogenerated file and will be overwritten by
 * the extension interface script.
 */
#ifndef S3EANDROIDAPPIRATER_AUTODEFS_H
#define S3EANDROIDAPPIRATER_AUTODEFS_H

/**
 * string name used to locate this extension
 */
#define S3E_EXT_ANDROIDAPPIRATER_NAME "s3eAndroidAppirater"
#define S3E_EXT_ANDROIDAPPIRATER_HASH 0xf598d199

#endif /* !S3EANDROIDAPPIRATER_AUTODEFS_H */
