/*
 * WARNING: this is an autogenerated file and will be overwritten by
 * the extension interface script.
 */
/*
 * This file contains the automatically generated loader-side
 * functions that form part of the extension.
 *
 * This file is awlays compiled into all loaders but compiles
 * to nothing if this extension is not enabled in the loader
 * at build time.
 */
#include "IwDebug.h"
#include "s3eAndroidAppirater_autodefs.h"
#include "s3eEdk.h"
#include "s3eAndroidAppirater.h"
//Declarations of Init and Term functions
extern s3eResult s3eAndroidAppiraterInit();
extern void s3eAndroidAppiraterTerminate();


// On platforms that use a seperate UI/OS thread we can autowrap functions
// here.   Note that we can't use the S3E_USE_OS_THREAD define since this
// code is oftern build standalone, outside the main loader build.
#if defined I3D_OS_IPHONE || defined I3D_OS_OSX || defined I3D_OS_LINUX || defined I3D_OS_WINDOWS

static s3eResult AppiraterInit_wrap(const char* cTitle, const char* cAppName, int iDays, int iLaunches, int iEvents)
{
    IwTrace(ANDROIDAPPIRATER_VERBOSE, ("calling s3eAndroidAppirater func on main thread: AppiraterInit"));
    return (s3eResult)(intptr_t)s3eEdkThreadRunOnOS((s3eEdkThreadFunc)AppiraterInit, 5, cTitle, cAppName, iDays, iLaunches, iEvents);
}

static s3eResult AppiraterEventOccured_wrap()
{
    IwTrace(ANDROIDAPPIRATER_VERBOSE, ("calling s3eAndroidAppirater func on main thread: AppiraterEventOccured"));
    return (s3eResult)(intptr_t)s3eEdkThreadRunOnOS((s3eEdkThreadFunc)AppiraterEventOccured, 0);
}

#define AppiraterInit AppiraterInit_wrap
#define AppiraterEventOccured AppiraterEventOccured_wrap

#endif

void s3eAndroidAppiraterRegisterExt()
{
    /* fill in the function pointer struct for this extension */
    void* funcPtrs[2];
    funcPtrs[0] = (void*)AppiraterInit;
    funcPtrs[1] = (void*)AppiraterEventOccured;

    /*
     * Flags that specify the extension's use of locking and stackswitching
     */
    int flags[2] = { 0 };

    /*
     * Register the extension
     */
    s3eEdkRegister("s3eAndroidAppirater", funcPtrs, sizeof(funcPtrs), flags, s3eAndroidAppiraterInit, s3eAndroidAppiraterTerminate, 0);
}

#if !defined S3E_BUILD_S3ELOADER

#if defined S3E_EDK_USE_STATIC_INIT_ARRAY
int s3eAndroidAppiraterStaticInit()
{
    void** p = g_StaticInitArray;
    void* end = p + g_StaticArrayLen;
    while (*p) p++;
    if (p < end)
        *p = (void*)&s3eAndroidAppiraterRegisterExt;
    return 0;
}

int g_s3eAndroidAppiraterVal = s3eAndroidAppiraterStaticInit();

#elif defined S3E_EDK_USE_DLLS
S3E_EXTERN_C S3E_DLL_EXPORT void RegisterExt()
{
    s3eAndroidAppiraterRegisterExt();
}
#endif

#endif
